### ISSUE TITLE
A way to reset initial route

### ISSUE THREAD

**Issue by sercanov** [MikaelCarpenter/gb-native-router#1]
Hi there,

I've been trying to do a login page, after user logged in, I push view to home screen but user can go back with backswipe or back button. Is there any way to block this ?

**Comment by MikaelCarpenter** [comment]
Yup definitely possible, that's what I'm working on next. For right now the hacky way to do it is pass `View` to left corner when you navigate to get rid of the back button and then disable swipe back if `route.index === 1`.

The proper way to do it is to enable the ability to reset the route stack. If you want to try working that out you can submit a PR and I'll merge it. Or you can wait till Tuesday and I should have a PR out for it. :)

**Comment by MikaelCarpenter** [comment]
@sercanov I've added the functionallity that you need. You can check out the [PR](https://github.com/MikaelCarpenter/gb-native-router/pull/2) to see what it is, but basically on successful login, instead of using `this.props.toRoute`, you can use `this.props.replaceRoute` and the user won't be able to get back to the login screen.
